#! /bin/sh

# You want to use sudo.

root=/home/$USER/bin/root
if [ ! -f $root ]; then
	root=sudo
fi

dir=$(dirname $0)

$root chvt 1
$root chmod 666 /dev/tty1
$dir/rss.pl -ticker </dev/tty1 >/dev/tty1 &
